### ISSUE TITLE
CIの導入

### ISSUE THREAD

**Issue by snickerjp** [oracle-cloud-friends/solution-guide#1]
CIでも、コードレビューについて、
当社でも使っているサービスを、導入してみてはどうでしょうか？

理由：
* 少ない人数のうちから、枠組みを「ある程度」決める
* 大まかな、フォーマットを強制してくれる

など、結構いいことが多いので、提案してみました。

* こちらです -> [Automated code reviews & code analytics \| Codacy](https://www.codacy.com/)

**Comment by snickerjp** [comment]
試しに、Cloneした自分のリポジトリを読み込ませてみました。

* こちら -> [solution\-guide \- Codacy \- Dashboard](https://app.codacy.com/project/snickerjp/solution-guide/dashboard)

**Comment by tazyamah** [comment]
@snickerjp 利用サービス自体にあまりこだわりはないのですが、人数増えてきたら提示されたサービスは有料になっちゃうのが痛いと思っています。
例えばオープンソースであることを維持し続ける(その予定のつもりです)のであれば、TravisCIは無料なのでソッチのほうが良いかな、と。

手が回っていなくてCI対応できていないのですが、毎回手作業でdocsを生成するのはなんだかなーというのがあるので、masterにマージされたら勝手にdocsのビルドをしてくれるみたいな感じがいいですね＾＾

**Comment by snickerjp** [comment]
Codacy 4userまでなんですね！
知りませんでした。

- TravisCI
- CircleCI

が、ちゃんと使ったことがなくて。

- Codacy

は、レビューサービスみたいな感じなので。
lintがプルリクエストの範囲でやってくれるとか。

- Markdown
- Dockerfile

に対応しているとか。結構便利です。
提案程度なので、Closeしてもらって大丈夫ですー

**Comment by tazyamah** [comment]
@snickerjp せっかくなのでトライしてみるというのもありだと思います・・・！(が、やる気ドリブンではあるので、気乗りしなければ一旦closeさせちゃってください
直近の僕は小さなスキマ時間しか作業に当てられないので、CI導入とかのまとまった時間がほしいタスクは尻込みしてしまう・・・

**Comment by snickerjp** [comment]
Closeで大丈夫ですー

自分のリポジトリでは、動いているので。
